---
# Per environment values which override defaults in hmpps-single-accommodation-service-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: single-accommodation-service-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-single-accommodation-service-dev-cert

  env:
    INGRESS_URL: "https://single-accommodation-service-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SAS_API_URL: 'https://single-accommodation-service-api-dev.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"
    COMPONENT_API_URL: "https://probation-frontend-components-dev.hmpps.service.justice.gov.uk"
    SAS_ALLOWED_ROLES: "ROLE_PROBATION"

generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises
