---
# Per environment values which override defaults in hmpps-single-accommodation-service-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: single-accommodation-service-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-single-accommodation-service-preprod-cert

  env:
    INGRESS_URL: "https://single-accommodation-service-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    SAS_API_URL: 'https://single-accommodation-service-api-preprod.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"
    COMPONENT_API_URL: "https://probation-frontend-components-preprod.hmpps.service.justice.gov.uk"
    SAS_ALLOWED_ROLES: "ROLE_SINGLE_ACCOMMODATION_SERVICE_PROBATION_PRACTITIONER"

generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises
