---
# Per environment values which override defaults in hmpps-single-accommodation-service-ui/values.yaml

generic-service:
  ingress:
    host: single-accommodation-service-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://single-accommodation-service-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    SAS_API_URL: 'https://single-accommodation-service-api.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"
    COMPONENT_API_URL: "https://probation-frontend-components.hmpps.service.justice.gov.uk"
    SAS_ALLOWED_ROLES: "ROLE_SAS"

generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises
